### ISSUE TITLE
Config file not taken into account

### ISSUE THREAD

**Issue by fchabouis** [ITxPT/DATA4PTTools#18]
Hello,

I'm trying to launch the tool using a config file as follow:

```
docker run -it -v /home/francis/Downloads/TBM_NeTEx/bordeaux_metropole-aggregated-netex/OFFRE_bordeaux_metropole_20220302001237Z/BORDEAUX_METROPOLE_offre_Bus_1_54_54.xml:/greenlight/documents -v /home/francis/projects/transport/greenlight_validator/config.yaml:/greenlight/config.yaml lekojson/greenlight -i /greenlight

┌ /greenlight/documents ─╼
│ xsd ... ok
└───╼ 
```

The validation seems to be done successfuly. 
The config file contains the configuration given in example in the documentation:

```yaml
schema: xsd/NeTEx_publication.xsd # schema to use for validation, comes shipped with the source/container image
logLevel: debug # default is undefined, setting this parameter disables the fancy setting, regardless of its value
fancy: true # displays a progress instead of log
inputs: # where to look for documents
  - ~/.greenlight/documents
  - /etc/greenlight/documents
  - /documents
  - /greenlight/documents
  - ./documents
outputs:
  - report: # logged in standard output
      format: mdext # mdext (markdown extended) or mds (markdown simple)
  - file:
      format: json # formats available are: json or xml
      path: . # where to save the file (filename format is ${path}/report-${current_date_time}.${format}
builtin: true # whether to use builtin scripts
scripts: # where to look for custom scripts
  - ~/.greenlight/scripts
  - /etc/greenlight/scripts
  - /scripts
  - /greenlight/scripts
  - ./scripts
```

I am expecting to have a json output report generated in the current directory but I have none.
The only output I can see is the terminal output saying `ok`

Can you help me understand how to have access to a full output report?
Thanks
